services:
  # maven-api:
  #   image: maven-api
  #   container_name: maven-api
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env.docker
  #   ports:
  #     - '5000:5000'
  #   networks:
  #     - maven-exchange-network

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: maven_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'UTC'
    ports:
      - '5432:5432'
    networks:
      - maven-exchange-network

  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass redispass'
    networks:
      - maven-exchange-network

  # maildev:
  #   build:
  #     context: .
  #     dockerfile: maildev.Dockerfile
  #   ports:
  #     - ${MAIL_CLIENT_PORT}:1080
  #     - ${MAIL_PORT}:1025
  #   networks:
  #     - maven-exchange-network

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '18080:80'
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: 12345678
  #     PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
  #     PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
  #   networks:
  #     - maven-exchange-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  maven-exchange-network:
    driver: bridge
